name: mula_biz_mobile
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.2.0
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  dartz: 0.10.1
  retrofit: ^4.0.1
  logger: ^2.0.1

  copy_with_extension: ^5.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3

  #  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  connectivity_plus: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  #responsive
  flutter_screenutil: ^5.8.4
  flutter_gen: ^5.3.1

  infinite_scroll_pagination: ^4.0.0
  top_snackbar_flutter: ^3.1.0
  equatable: ^2.0.5
  shimmer: ^3.0.0
  event_bus: 2.0.0
  go_router: ^10.0.0
  flutter_alice: ^1.1.1
  pinput: ^3.0.0
  formz: ^0.6.0
  device_info_plus: ^9.0.3
  camera: ^0.10.5+4
  firebase_core: ^2.15.1
  fast_rsa: ^3.6.1
  awesome_snackbar_content: ^0.1.3
  flutter_animated_dialog: ^2.0.1
  mobile_scanner: ^3.5.2
  loading_animation_widget: ^1.2.0+4
  google_mlkit_face_detection: ^0.9.0
  convex_bottom_bar: ^3.2.0
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  copy_with_extension_gen: ^5.0.3
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: "^0.13.1"
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mula-icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/env/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700